### ISSUE TITLE
feature/198-set-custom-battery-level

### ISSUE THREAD

**Issue by toekneechin777** [swarm-robotics/rcppsw#198]
## Expected Behavior
Be able to set a specific amount of battery to the robot.

## Actual Behavior
Sets battery only to 100% charged everytime.

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications
  - Version:
  - Platform:
  - Subsystem:

**Comment by jharwell** [comment]
OBE. Got this working.
